<div class="clearfix">
	<span>
		<?php echo __( 'Tags', Thrive_Quiz_Builder::T ) ?>
	</span>
	<div class="tge-tag-tooltip">
		<i class="tvd-icon-question-circle"></i>
		<div class="tge-info-tooltip">
			<?php echo __( 'Visitors who choose this answer will be assigned the following tags.', Thrive_Quiz_Builder::T ) ?>
		</div>
	</div>
</div>
<div class="clearfix">
	<div class="tvd-input-field tqb-tags-input">
		<input class="tvd-skip-modal-save" id="<#= item.cid #>" type="text" value="<#= item.get('tags') #>" data-bind="tags" placeholder="<?php echo __( 'Add your tags here', Thrive_Quiz_Builder::T ) ?>">
	</div>
</div>
