<div class="tge-image-form">
	<div class="tge-image-placeholder"></div>

	<div class="tge-image-overlay"></div>

	<a href="javascript:void(0)" class="tge-add-image">
		<?php echo __( 'Add Image', Thrive_Quiz_Builder::T ) ?>
	</a>

	<a class="tge-remove-image tvd-white-text" href="javascript:void(0)">
		<i class="tvd-icon-trash-o tvd-pointer"></i>
	</a>
	<a class="tge-change-image tvd-white-text" href="javascript:void(0)">
		<?php echo __( 'Change<br/>Image', Thrive_Graph_Editor::T ) ?>
	</a>
</div>
