<div class="tqb-reset-quiz-card-modal">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title">
			<?php echo __( 'Reset ', Thrive_Quiz_Builder::T ); ?>
		</h3>
		<p>
			<span class="tqb-has-placeholder"><?php echo sprintf( __( 'Warning! You are about to reset all statistics for %s!', Thrive_Quiz_Builder::T ), '<strong>%s</strong>' ) ?></span><br/>
			<?php echo sprintf( __( "The reports for %s will display the data since the last reset. Your variations statistics won't be affected by this. Do you want to continue?", Thrive_Quiz_Builder::T ), '<strong>%s</strong>' ) ?>
		</p>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
					<?php echo __( 'Cancel', Thrive_Quiz_Builder::T ); ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn tvd-btn-red tvd-waves-light tvd-right tvd-modal-submit">
					<?php echo __( 'Reset stats', Thrive_Quiz_Builder::T ); ?>
				</a>
			</div>
		</div>
	</div>
</div>
