<div class="tvd-row">
	<div class="tvd-col tvd-s1" >
		<span class="tqb-answer-color" style="background-color:<#= item.get('color') #>" ></span>
	</div>
	<div class="tvd-col tvd-s5" style="color:<#= item.get('color') #>">
		<# if( item.get('image').url ) { #>
			<img height="100" src="<#= item.get('image').url #>" alt="" class="tqb-answer-image">
		<# } else { #>
			<#= item.get('text') #>
		<# } #>
	</div>
	<div class="tvd-col tvd-s3">
		<#= item.get('count') #>
	</div>
	<div class="tvd-col tvd-s3">
		<#= item.get('percent') #>%
	</div>
</div>