<p><strong><?php echo __( 'ThriveBox Settings', 'thrive-cb' ) ?></strong></p>
<# if ( this.get().length ) { #>
	<div class="row top-xs">
		<div class="col-xs-7">
			<label for="evt-lightbox"><?php echo __( 'Select the ThriveBox to be displayed', 'thrive-cb' ) ?></label>
		</div>
		<div class="col-xs-5">
			<select id="evt-lightbox" class="change" data-fn="lightbox_change">
				<# _.each( this.get(), function( lb ) { #>
					<option value="<#=lb.id#>"<#=this.model.config && this.model.config.l_id == lb.id ? ' selected="selected"' : '' #>><#=lb.title#></option>
				<# }, this ) #>
			</select>
		</div>
	</div>
	<# } else { #>
		<p><?php echo sprintf( __( "You don't have any Thrive Boxes created yet. You can create them from %s", 'thrive-cb' ), '<a target="_blank" href="' . admin_url( 'admin.php?page=thrive_leads_dashboard' ) . '">Thrive Leads</a>' ) ?></p>
	<# } #>
