<div class="text-typefocus">
	<div class="row middle-xs">
		<div class="col-xs-9">
			<span class="input-label"><?php echo __( 'Typefocus animation', 'thrive-cb' ); ?></span>
		</div>
		<div class="col-xs-3 tcb-text-right state-toggle state-add">
			<div class="blue tve-button click" data-fn="open_settings"><?php echo __( 'Add', 'thrive-cb' ); ?></div>
		</div>
	</div>
	<div id="typefocus-preview" class="tcb-relative tcb-preview-list" style="padding:0"></div>
</div>